<<<<<<< HEAD
# =============================================
# CONFIGURACIÓN - ZAPATERÍA ONLINE
# =============================================
spring.application.name=zapateria-tienda

# =============================================
# MONGODB ATLAS
# =============================================
spring.data.mongodb.uri=mongodb+srv://ejmaigua1_db_user:123456d@cluster0.gywuszl.mongodb.net/zapateria_db?retryWrites=true&w=majority&appName=Cluster0

# =============================================
# SERVIDOR
# =============================================
server.port=8080

spring.jackson.time-zone=America/Guayaquil

# =============================================
# RECURSOS ESTÁTICOS
# =============================================
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# =============================================
# ADMIN POR DEFECTO
# =============================================
app.admin.username=admin
app.admin.password=admin123
app.admin.email=admin@zapateria.com
app.admin.nombre=Administrador
app.admin.apellido=Sistema
app.admin.telefono=0999999999

# =============================================
# LOGGING
# =============================================
logging.level.root=INFO
logging.level.com.zapateria=DEBUG
=======
server.port=8080
spring.application.name=zapateria-tienda

spring.data.mongodb.uri=mongodb+srv://ejmaigua1_db_user:123456d@cluster0.gywuszl.mongodb.net/zapateria_db?retryWrites=true&w=majority&appName=Cluster0

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
>>>>>>> a09a18c754bf93d4a0edc2246d392dfb48fed16a
